In [19]:
! pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Маска

Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X, строго превышающих значение limit, которое является входным значением алгоритма.

Входная матрица: X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Sample Input:

1
Sample Output:

tensor(44)

In [10]:
import torch

X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = X[X > limit].sum()

print(larger_than_limit_sum)

1
tensor(44)


# Градиентный спуск
requires_grad - ищем производную по тензору

backward - считаем производную (идём с конца)

храним свам результат в переменной !

In [21]:
  import torch

  x = torch.tensor([[1., 2., 3., 4.],
                    [5., 6., 7., 8.],
                    [9., 10., 11., 12.]], requires_grad=True)
  
  ###
  device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

  x = x.to(device)
  ###

  function = 10 * (x ** 2).sum()

  function.backward()

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


In [23]:
x, function

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]], requires_grad=True),
 tensor(0.5463, grad_fn=<ProdBackward0>))

In [24]:
print(x.grad, '<- gradient')

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


здесь происходит обновление тензора x:

x.grad - градиент, хранящийся в тензоре x

шаг - 0.001

x.data - обновление тензора x (обновление данных, но requires_grad=False), результатом является сумма предыдущего и текущего градиентов и для того чтобы это не происходило, обнуляем с помощью x.grad.zero_()

In [25]:
x.data -= 0.001 * x.grad

In [26]:
x.grad.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
x.data

tensor([[ 0.9800,  1.9600,  2.9400,  3.9200],
        [ 4.9000,  5.8800,  6.8600,  7.8400],
        [ 8.8200,  9.8000, 10.7800, 11.7600]])

## Реализуйте расчёт градиента для функции F(w)
w = [[5, 10], [1, 2]]

f(w) = П(i,j)loge(loge(w[i,j] + 7 ))

torch.prod - ряд произведения (П) 

In [22]:
import torch

w = torch.tensor([[5., 10.],
                  [1., 2.]], requires_grad=True)

function = torch.prod(torch.log(torch.log(w + 7)))
function.backward()

print(w.grad, '<- gradient')

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]]) <- gradient


## Реализуйте расчёт градиента для функции F(w) Часть № 2

пусть начальное значение w = [[5, 10], [1, 2]]

альфа(шаг) = 0.001

узнать чему будет равно w при t = 500

формула: f(w) = П(i,j)loge(loge(w[i,j] + 7))

In [34]:
import torch

w = torch.tensor([[5., 10.],
                  [1., 2.,]], requires_grad=True)

alpha = 0.001

for _ in range(500):
  function = torch.prod(torch.log(torch.log(w + 7)))
  function.backward()
  w.data -= alpha * w.grad
  w.grad.zero_()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)
